In [46]:
from tensorflow.keras.models import load_model

In [47]:
import numpy as np

In [48]:
import joblib

In [49]:
nn_model=load_model("bank_churn.h5")

In [50]:
nn_model

<Sequential name=sequential, built=True>

In [51]:
sc=joblib.load("bank_scaler.pkl")

In [52]:
sc

StandardScaler()

In [53]:
#REAL TIME PREDICTION

In [54]:
new_customer=[[716.0, 48.0, 10.0, 137452.09, 1.0, 1.0, 0.0, 189543.9, 1.0, 0.0, 1.0]]

In [55]:
type(new_customer)

list

In [56]:
new_customer=np.array(new_customer)

In [57]:
new_customer

array([[   716.  ,     48.  ,     10.  , 137452.09,      1.  ,      1.  ,
             0.  , 189543.9 ,      1.  ,      0.  ,      1.  ]])

In [58]:
np.set_printoptions(precision=2,suppress=True)

In [59]:
new_customer

array([[   716.  ,     48.  ,     10.  , 137452.09,      1.  ,      1.  ,
             0.  , 189543.9 ,      1.  ,      0.  ,      1.  ]])

In [60]:
new_customer=sc.transform(new_customer)

E:\Users\gunit\anaconda3\pkgs\anaconda3py310\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [66]:
predict=nn_model.predict(new_customer)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


In [67]:
predict

array([[0.52]], dtype=float32)

In [68]:
predict=predict > 0.5

In [69]:
predict

array([[ True]])

In [62]:
#in the form of function

In [63]:
def predict_churn(customer_data):
    customer_data=np.array(customer_data)
    customer_data=sc.transform(customer_data)
    prediction=nn_model.predict(customer_data)
    prediction=prediction > 0.5
    return prediction

In [64]:
new_customer2=[[703.0, 42.0, 9.0, 63227.0, 1.0, 0.0, 1.0, 137316.32, 1.0, 0.0, 1.0]]

In [65]:
predict_churn(new_customer2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


E:\Users\gunit\anaconda3\pkgs\anaconda3py310\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[False]])